
[functions.extract-keywords]
enabled = true
verify_jwt = true
import_map = "./functions/extract-keywords/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/extract-keywords/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/extract-keywords/*.html" ]

[functions.batch-extract-keywords]
enabled = true
verify_jwt = true
import_map = "./functions/batch-extract-keywords/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/batch-extract-keywords/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/batch-extract-keywords/*.html" ]
